### ISSUE TITLE
Preparar el pitch del proyecto

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo5_cv_ppi2020#7]

**Comment by JohnFlorez25** [comment]
@MariaJoseVegaGuerrero @CinthiaSerna2020. @Brayan-T Se debe subir las diapositivas del pitch y el protocol en excel en la wiki, les recomiendo colocarlos con una etiqueta de ancla `<a href="" >Link </a>`

**Comment by CinthiaSerna2020** [comment]
Profe acabo de subir lo del Pitch del proyecto. Créame las diapositivas se ven mucho mejor si descarga la presentación ;)
